/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPartsAiRouteImport } from './routes/_authenticated/parts-ai'
import { Route as AuthenticatedHistoricoRouteImport } from './routes/_authenticated/historico'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedBuscaRouteImport } from './routes/_authenticated/busca'
import { Route as AuthenticatedPecaIdRouteImport } from './routes/_authenticated/peca.$id'
import { Route as AuthenticatedCatalogoVinRouteImport } from './routes/_authenticated/catalogo.$vin'
import { Route as AuthenticatedAdminImportarRouteImport } from './routes/_authenticated/admin.importar'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPartsAiRoute = AuthenticatedPartsAiRouteImport.update({
  id: '/parts-ai',
  path: '/parts-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoricoRoute = AuthenticatedHistoricoRouteImport.update({
  id: '/historico',
  path: '/historico',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuscaRoute = AuthenticatedBuscaRouteImport.update({
  id: '/busca',
  path: '/busca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPecaIdRoute = AuthenticatedPecaIdRouteImport.update({
  id: '/peca/$id',
  path: '/peca/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCatalogoVinRoute =
  AuthenticatedCatalogoVinRouteImport.update({
    id: '/catalogo/$vin',
    path: '/catalogo/$vin',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminImportarRoute =
  AuthenticatedAdminImportarRouteImport.update({
    id: '/admin/importar',
    path: '/admin/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/parts-ai': typeof AuthenticatedPartsAiRoute
  '/admin/importar': typeof AuthenticatedAdminImportarRoute
  '/catalogo/$vin': typeof AuthenticatedCatalogoVinRoute
  '/peca/$id': typeof AuthenticatedPecaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/busca': typeof AuthenticatedBuscaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/historico': typeof AuthenticatedHistoricoRoute
  '/parts-ai': typeof AuthenticatedPartsAiRoute
  '/admin/importar': typeof AuthenticatedAdminImportarRoute
  '/catalogo/$vin': typeof AuthenticatedCatalogoVinRoute
  '/peca/$id': typeof AuthenticatedPecaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/busca': typeof AuthenticatedBuscaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/historico': typeof AuthenticatedHistoricoRoute
  '/_authenticated/parts-ai': typeof AuthenticatedPartsAiRoute
  '/_authenticated/admin/importar': typeof AuthenticatedAdminImportarRoute
  '/_authenticated/catalogo/$vin': typeof AuthenticatedCatalogoVinRoute
  '/_authenticated/peca/$id': typeof AuthenticatedPecaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/busca'
    | '/dashboard'
    | '/historico'
    | '/parts-ai'
    | '/admin/importar'
    | '/catalogo/$vin'
    | '/peca/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/busca'
    | '/dashboard'
    | '/historico'
    | '/parts-ai'
    | '/admin/importar'
    | '/catalogo/$vin'
    | '/peca/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/busca'
    | '/_authenticated/dashboard'
    | '/_authenticated/historico'
    | '/_authenticated/parts-ai'
    | '/_authenticated/admin/importar'
    | '/_authenticated/catalogo/$vin'
    | '/_authenticated/peca/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/parts-ai': {
      id: '/_authenticated/parts-ai'
      path: '/parts-ai'
      fullPath: '/parts-ai'
      preLoaderRoute: typeof AuthenticatedPartsAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/historico': {
      id: '/_authenticated/historico'
      path: '/historico'
      fullPath: '/historico'
      preLoaderRoute: typeof AuthenticatedHistoricoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/busca': {
      id: '/_authenticated/busca'
      path: '/busca'
      fullPath: '/busca'
      preLoaderRoute: typeof AuthenticatedBuscaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/peca/$id': {
      id: '/_authenticated/peca/$id'
      path: '/peca/$id'
      fullPath: '/peca/$id'
      preLoaderRoute: typeof AuthenticatedPecaIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/catalogo/$vin': {
      id: '/_authenticated/catalogo/$vin'
      path: '/catalogo/$vin'
      fullPath: '/catalogo/$vin'
      preLoaderRoute: typeof AuthenticatedCatalogoVinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/importar': {
      id: '/_authenticated/admin/importar'
      path: '/admin/importar'
      fullPath: '/admin/importar'
      preLoaderRoute: typeof AuthenticatedAdminImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuscaRoute: typeof AuthenticatedBuscaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoricoRoute: typeof AuthenticatedHistoricoRoute
  AuthenticatedPartsAiRoute: typeof AuthenticatedPartsAiRoute
  AuthenticatedAdminImportarRoute: typeof AuthenticatedAdminImportarRoute
  AuthenticatedCatalogoVinRoute: typeof AuthenticatedCatalogoVinRoute
  AuthenticatedPecaIdRoute: typeof AuthenticatedPecaIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuscaRoute: AuthenticatedBuscaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoricoRoute: AuthenticatedHistoricoRoute,
  AuthenticatedPartsAiRoute: AuthenticatedPartsAiRoute,
  AuthenticatedAdminImportarRoute: AuthenticatedAdminImportarRoute,
  AuthenticatedCatalogoVinRoute: AuthenticatedCatalogoVinRoute,
  AuthenticatedPecaIdRoute: AuthenticatedPecaIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
